apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: water-rationing
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: water-rationing-token
